# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MakeQr")
        MainWindow.resize(500, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_link = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_link.setGeometry(QtCore.QRect(100, 10, 381, 31))
        self.lineEdit_link.setObjectName("lineEdit_link")
        self.pushButton_inputlink = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_inputlink.setGeometry(QtCore.QRect(2, 10, 91, 31))
        self.pushButton_inputlink.setObjectName("pushButton_inputlink")
        self.label_Qr = QtWidgets.QLabel(self.centralwidget)
        self.label_Qr.setGeometry(QtCore.QRect(140, 70, 300, 300))
        self.label_Qr.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Qr.setText("")
        self.label_Qr.setObjectName("label_Qr")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MakeQr", "MakeQr"))
        self.pushButton_inputlink.setText(_translate("Link to Qr", "Nhập"))
